// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs convert-color`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "convert-timestamp",
    "icon": "⏱️",
    "name": {
      "en": "Convert Timestamp",
      "ja": "タイムスタンプ変換",
      "zh": "转换时间戳",
      "de": "Zeitstempel umwandeln",
      "es": "Convertir marca de tiempo"
    },
    "desc": {
      "en": "Convert between Unix timestamps and human-readable dates.",
      "ja": "Unixタイムスタンプと日時表記を相互変換。",
      "zh": "在 Unix 时间戳与可读日期之间转换。",
      "de": "Unix-Zeitstempel und lesbare Datumsangaben ineinander umwandeln.",
      "es": "Convierte entre marcas de tiempo Unix y fechas legibles."
    }
  },
  {
    "slug": "format-json",
    "icon": "📐",
    "name": {
      "en": "Format JSON",
      "ja": "JSON整形",
      "zh": "格式化 JSON",
      "de": "JSON formatieren",
      "es": "Formatear JSON"
    },
    "desc": {
      "en": "Pretty-print, validate, or minify JSON.",
      "ja": "JSONを整形・検証・圧縮。",
      "zh": "美化打印、校验或压缩 JSON。",
      "de": "JSON formatieren, validieren oder minimieren.",
      "es": "Formatea, valida o minifica JSON."
    }
  },
  {
    "slug": "encode-base64",
    "icon": "🔤",
    "name": {
      "en": "Encode Base64",
      "ja": "Base64エンコード",
      "zh": "Base64 编解码",
      "de": "Base64 kodieren",
      "es": "Codificar Base64"
    },
    "desc": {
      "en": "Encode or decode Base64, for text or binary files, byte-for-byte.",
      "ja": "テキスト・バイナリファイルをBase64に相互変換。バイト完全一致。",
      "zh": "对文本或二进制文件进行 Base64 编码或解码，逐字节还原。",
      "de": "Base64 für Text- oder Binärdateien kodieren oder dekodieren, Byte für Byte.",
      "es": "Codifica o decodifica Base64 para texto o archivos binarios, byte a byte."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'convert-color';
